name: First Workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: Multiline commands
        run: |
          node -v
          npm -v
      - name: Testing Error
        run: ps -ef |grep -i network
  parallel-job-macos:
      runs-on: macos-latest
      steps:
        - name: View SW version
          run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output "Windows String"

    

